### ISSUE TITLE
update readme with the latest roadmap

### ISSUE THREAD

**Issue by midnqp** [MidnQP/TerminalChat#28]
- non-blocking text messages supported
- markdown supported
- voice calls supported

nothing else planned as of November 2023.

for images: https://npmjs.com/package/terminal-image
for voice messages: check one of your previous branches

**Comment by midnqp** [comment]
- [x] add usage
- [x] add installation
- [x] tried to install a typescript npm package with its binary - doesn't work :(
- [x] compiled from typescript, then `npm pack` and `npm publish`
- [x] installed and tested
- [ ] found bug with username change
- [ ] add readme section 'how it works'
